//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::transfer_history::Entity as TransferHistory;
pub use super::transfers::Entity as Transfers;
pub use super::users::Entity as Users;
